package com.slianOAsys.admin.utils;

import java.util.Date;

public class TransEquipment {
	 private Integer equipmentId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.producer_id
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String producerId;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.equipment_name
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String equipmentName;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.equipment_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String equipmentCode;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.QR_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String qrCode;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.location
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String location;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.longitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private Double longitude;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.latitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private Double latitude;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.equipment_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String equipmentStatus;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.mot_data
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String motData;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.add_time
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private String addTime;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.mot_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private Integer motStatus;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column equipment.is_inspected
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    private Integer isInspected;

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.equipment_id
	     *
	     * @return the value of equipment.equipment_id
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public Integer getEquipmentId() {
	        return equipmentId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.equipment_id
	     *
	     * @param equipmentId the value for equipment.equipment_id
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setEquipmentId(Integer equipmentId) {
	        this.equipmentId = equipmentId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.producer_id
	     *
	     * @return the value of equipment.producer_id
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getProducerId() {
	        return producerId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.producer_id
	     *
	     * @param producerId the value for equipment.producer_id
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setProducerId(String producerId) {
	        this.producerId = producerId;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.equipment_name
	     *
	     * @return the value of equipment.equipment_name
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getEquipmentName() {
	        return equipmentName;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.equipment_name
	     *
	     * @param equipmentName the value for equipment.equipment_name
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setEquipmentName(String equipmentName) {
	        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.equipment_code
	     *
	     * @return the value of equipment.equipment_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getEquipmentCode() {
	        return equipmentCode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.equipment_code
	     *
	     * @param equipmentCode the value for equipment.equipment_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setEquipmentCode(String equipmentCode) {
	        this.equipmentCode = equipmentCode == null ? null : equipmentCode.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.QR_code
	     *
	     * @return the value of equipment.QR_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getQrCode() {
	        return qrCode;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.QR_code
	     *
	     * @param qrCode the value for equipment.QR_code
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setQrCode(String qrCode) {
	        this.qrCode = qrCode == null ? null : qrCode.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.location
	     *
	     * @return the value of equipment.location
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getLocation() {
	        return location;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.location
	     *
	     * @param location the value for equipment.location
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setLocation(String location) {
	        this.location = location == null ? null : location.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.longitude
	     *
	     * @return the value of equipment.longitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public Double getLongitude() {
	        return longitude;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.longitude
	     *
	     * @param longitude the value for equipment.longitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setLongitude(Double longitude) {
	        this.longitude = longitude;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.latitude
	     *
	     * @return the value of equipment.latitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public Double getLatitude() {
	        return latitude;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.latitude
	     *
	     * @param latitude the value for equipment.latitude
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setLatitude(Double latitude) {
	        this.latitude = latitude;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.equipment_status
	     *
	     * @return the value of equipment.equipment_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getEquipmentStatus() {
	        return equipmentStatus;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.equipment_status
	     *
	     * @param equipmentStatus the value for equipment.equipment_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setEquipmentStatus(String equipmentStatus) {
	        this.equipmentStatus = equipmentStatus == null ? null : equipmentStatus.trim();
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.mot_data
	     *
	     * @return the value of equipment.mot_data
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getMotData() {
	        return motData;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.mot_data
	     *
	     * @param motData the value for equipment.mot_data
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setMotData(String motData) {
	        this.motData = motData;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.add_time
	     *
	     * @return the value of equipment.add_time
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public String getAddTime() {
	        return addTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.add_time
	     *
	     * @param addTime the value for equipment.add_time
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setAddTime(String addTime) {
	        this.addTime = addTime;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.mot_status
	     *
	     * @return the value of equipment.mot_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public Integer getMotStatus() {
	        return motStatus;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.mot_status
	     *
	     * @param motStatus the value for equipment.mot_status
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setMotStatus(Integer motStatus) {
	        this.motStatus = motStatus;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method returns the value of the database column equipment.is_inspected
	     *
	     * @return the value of equipment.is_inspected
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public Integer getIsInspected() {
	        return isInspected;
	    }

	    /**
	     * This method was generated by MyBatis Generator.
	     * This method sets the value of the database column equipment.is_inspected
	     *
	     * @param isInspected the value for equipment.is_inspected
	     *
	     * @mbggenerated Thu Sep 24 21:51:02 CST 2015
	     */
	    public void setIsInspected(Integer isInspected) {
	        this.isInspected = isInspected;
	    }
}
