package com.slianOAsys.model;

import java.math.BigDecimal;

public class InspectionRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.record_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private BigDecimal recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.equipment_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private Integer equipmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.record_time
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String recordTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.inspector_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private Integer inspectorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.record_longtitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private Double recordLongtitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.record_latitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private Double recordLatitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.temperature_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String temperatureIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.temperature_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String temperatureOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.pressure
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String pressure;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_1
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_2
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_3
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_4
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_5
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_6
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_7
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_8
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_9
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_10
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_11
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_12
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter12;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_13
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter13;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_14
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter14;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_15
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter15;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.paremeter_16
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String paremeter16;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.parameter_17
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String parameter17;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.record_status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String recordStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.from_user_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String fromUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.equipment_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String equipmentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.inspector_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String inspectorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.temperature_cold_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String temperatureColdIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column inspection_record.temperature_cold_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	private String temperatureColdOut;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.record_id
	 * @return  the value of inspection_record.record_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public BigDecimal getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.record_id
	 * @param recordId  the value for inspection_record.record_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setRecordId(BigDecimal recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.equipment_id
	 * @return  the value of inspection_record.equipment_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public Integer getEquipmentId() {
		return equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.equipment_id
	 * @param equipmentId  the value for inspection_record.equipment_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setEquipmentId(Integer equipmentId) {
		this.equipmentId = equipmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.record_time
	 * @return  the value of inspection_record.record_time
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getRecordTime() {
		return recordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.record_time
	 * @param recordTime  the value for inspection_record.record_time
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setRecordTime(String recordTime) {
		this.recordTime = recordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.inspector_id
	 * @return  the value of inspection_record.inspector_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public Integer getInspectorId() {
		return inspectorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.inspector_id
	 * @param inspectorId  the value for inspection_record.inspector_id
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setInspectorId(Integer inspectorId) {
		this.inspectorId = inspectorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.status
	 * @return  the value of inspection_record.status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.status
	 * @param status  the value for inspection_record.status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.record_longtitude
	 * @return  the value of inspection_record.record_longtitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public Double getRecordLongtitude() {
		return recordLongtitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.record_longtitude
	 * @param recordLongtitude  the value for inspection_record.record_longtitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setRecordLongtitude(Double recordLongtitude) {
		this.recordLongtitude = recordLongtitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.record_latitude
	 * @return  the value of inspection_record.record_latitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public Double getRecordLatitude() {
		return recordLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.record_latitude
	 * @param recordLatitude  the value for inspection_record.record_latitude
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setRecordLatitude(Double recordLatitude) {
		this.recordLatitude = recordLatitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.temperature_in
	 * @return  the value of inspection_record.temperature_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getTemperatureIn() {
		return temperatureIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.temperature_in
	 * @param temperatureIn  the value for inspection_record.temperature_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setTemperatureIn(String temperatureIn) {
		this.temperatureIn = temperatureIn == null ? null : temperatureIn
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.temperature_out
	 * @return  the value of inspection_record.temperature_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getTemperatureOut() {
		return temperatureOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.temperature_out
	 * @param temperatureOut  the value for inspection_record.temperature_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setTemperatureOut(String temperatureOut) {
		this.temperatureOut = temperatureOut == null ? null : temperatureOut
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.pressure
	 * @return  the value of inspection_record.pressure
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getPressure() {
		return pressure;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.pressure
	 * @param pressure  the value for inspection_record.pressure
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setPressure(String pressure) {
		this.pressure = pressure == null ? null : pressure.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_1
	 * @return  the value of inspection_record.parameter_1
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter1() {
		return parameter1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_1
	 * @param parameter1  the value for inspection_record.parameter_1
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1 == null ? null : parameter1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_2
	 * @return  the value of inspection_record.parameter_2
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter2() {
		return parameter2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_2
	 * @param parameter2  the value for inspection_record.parameter_2
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2 == null ? null : parameter2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_3
	 * @return  the value of inspection_record.parameter_3
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter3() {
		return parameter3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_3
	 * @param parameter3  the value for inspection_record.parameter_3
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter3(String parameter3) {
		this.parameter3 = parameter3 == null ? null : parameter3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_4
	 * @return  the value of inspection_record.parameter_4
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter4() {
		return parameter4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_4
	 * @param parameter4  the value for inspection_record.parameter_4
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter4(String parameter4) {
		this.parameter4 = parameter4 == null ? null : parameter4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_5
	 * @return  the value of inspection_record.parameter_5
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter5() {
		return parameter5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_5
	 * @param parameter5  the value for inspection_record.parameter_5
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter5(String parameter5) {
		this.parameter5 = parameter5 == null ? null : parameter5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_6
	 * @return  the value of inspection_record.parameter_6
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter6() {
		return parameter6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_6
	 * @param parameter6  the value for inspection_record.parameter_6
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter6(String parameter6) {
		this.parameter6 = parameter6 == null ? null : parameter6.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_7
	 * @return  the value of inspection_record.parameter_7
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter7() {
		return parameter7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_7
	 * @param parameter7  the value for inspection_record.parameter_7
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter7(String parameter7) {
		this.parameter7 = parameter7 == null ? null : parameter7.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_8
	 * @return  the value of inspection_record.parameter_8
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter8() {
		return parameter8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_8
	 * @param parameter8  the value for inspection_record.parameter_8
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter8(String parameter8) {
		this.parameter8 = parameter8 == null ? null : parameter8.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_9
	 * @return  the value of inspection_record.parameter_9
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter9() {
		return parameter9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_9
	 * @param parameter9  the value for inspection_record.parameter_9
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter9(String parameter9) {
		this.parameter9 = parameter9 == null ? null : parameter9.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_10
	 * @return  the value of inspection_record.parameter_10
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter10() {
		return parameter10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_10
	 * @param parameter10  the value for inspection_record.parameter_10
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter10(String parameter10) {
		this.parameter10 = parameter10 == null ? null : parameter10.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_11
	 * @return  the value of inspection_record.parameter_11
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter11() {
		return parameter11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_11
	 * @param parameter11  the value for inspection_record.parameter_11
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter11(String parameter11) {
		this.parameter11 = parameter11 == null ? null : parameter11.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_12
	 * @return  the value of inspection_record.parameter_12
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter12() {
		return parameter12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_12
	 * @param parameter12  the value for inspection_record.parameter_12
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter12(String parameter12) {
		this.parameter12 = parameter12 == null ? null : parameter12.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_13
	 * @return  the value of inspection_record.parameter_13
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter13() {
		return parameter13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_13
	 * @param parameter13  the value for inspection_record.parameter_13
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter13(String parameter13) {
		this.parameter13 = parameter13 == null ? null : parameter13.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_14
	 * @return  the value of inspection_record.parameter_14
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter14() {
		return parameter14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_14
	 * @param parameter14  the value for inspection_record.parameter_14
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter14(String parameter14) {
		this.parameter14 = parameter14 == null ? null : parameter14.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_15
	 * @return  the value of inspection_record.parameter_15
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter15() {
		return parameter15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_15
	 * @param parameter15  the value for inspection_record.parameter_15
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter15(String parameter15) {
		this.parameter15 = parameter15 == null ? null : parameter15.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.paremeter_16
	 * @return  the value of inspection_record.paremeter_16
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParemeter16() {
		return paremeter16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.paremeter_16
	 * @param paremeter16  the value for inspection_record.paremeter_16
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParemeter16(String paremeter16) {
		this.paremeter16 = paremeter16 == null ? null : paremeter16.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.parameter_17
	 * @return  the value of inspection_record.parameter_17
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getParameter17() {
		return parameter17;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.parameter_17
	 * @param parameter17  the value for inspection_record.parameter_17
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setParameter17(String parameter17) {
		this.parameter17 = parameter17 == null ? null : parameter17.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.record_status
	 * @return  the value of inspection_record.record_status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getRecordStatus() {
		return recordStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.record_status
	 * @param recordStatus  the value for inspection_record.record_status
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus == null ? null : recordStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.from_user_name
	 * @return  the value of inspection_record.from_user_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getFromUserName() {
		return fromUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.from_user_name
	 * @param fromUserName  the value for inspection_record.from_user_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setFromUserName(String fromUserName) {
		this.fromUserName = fromUserName == null ? null : fromUserName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.equipment_name
	 * @return  the value of inspection_record.equipment_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getEquipmentName() {
		return equipmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.equipment_name
	 * @param equipmentName  the value for inspection_record.equipment_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName == null ? null : equipmentName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.inspector_name
	 * @return  the value of inspection_record.inspector_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getInspectorName() {
		return inspectorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.inspector_name
	 * @param inspectorName  the value for inspection_record.inspector_name
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setInspectorName(String inspectorName) {
		this.inspectorName = inspectorName == null ? null : inspectorName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.temperature_cold_in
	 * @return  the value of inspection_record.temperature_cold_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getTemperatureColdIn() {
		return temperatureColdIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.temperature_cold_in
	 * @param temperatureColdIn  the value for inspection_record.temperature_cold_in
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setTemperatureColdIn(String temperatureColdIn) {
		this.temperatureColdIn = temperatureColdIn == null ? null
				: temperatureColdIn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column inspection_record.temperature_cold_out
	 * @return  the value of inspection_record.temperature_cold_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public String getTemperatureColdOut() {
		return temperatureColdOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column inspection_record.temperature_cold_out
	 * @param temperatureColdOut  the value for inspection_record.temperature_cold_out
	 * @mbggenerated  Thu Dec 22 01:50:20 CST 2016
	 */
	public void setTemperatureColdOut(String temperatureColdOut) {
		this.temperatureColdOut = temperatureColdOut == null ? null
				: temperatureColdOut.trim();
	}
}