package com.slianOAsys.dao;

import com.slianOAsys.model.SignLocation;
import com.slianOAsys.model.SignLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SignLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int countByExample(SignLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int deleteByExample(SignLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int insert(SignLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int insertSelective(SignLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    List<SignLocation> selectByExample(SignLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    SignLocation selectByPrimaryKey(Integer status);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SignLocation record, @Param("example") SignLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SignLocation record, @Param("example") SignLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SignLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_location
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SignLocation record);
}