package com.slianOAsys.dao;

import com.slianOAsys.model.SlianoaEmployee;
import com.slianOAsys.model.SlianoaEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlianoaEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int countByExample(SlianoaEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int deleteByExample(SlianoaEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int insert(SlianoaEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int insertSelective(SlianoaEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    List<SlianoaEmployee> selectByExample(SlianoaEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    SlianoaEmployee selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SlianoaEmployee record, @Param("example") SlianoaEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SlianoaEmployee record, @Param("example") SlianoaEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SlianoaEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SlianoaEmployee record);
}