package com.slianOAsys.dao;

import com.slianOAsys.model.SlianoaAttendanceRecord;
import com.slianOAsys.model.SlianoaAttendanceRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlianoaAttendanceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int countByExample(SlianoaAttendanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int deleteByExample(SlianoaAttendanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int insert(SlianoaAttendanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int insertSelective(SlianoaAttendanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    List<SlianoaAttendanceRecord> selectByExample(SlianoaAttendanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    SlianoaAttendanceRecord selectByPrimaryKey(Integer recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SlianoaAttendanceRecord record, @Param("example") SlianoaAttendanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SlianoaAttendanceRecord record, @Param("example") SlianoaAttendanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SlianoaAttendanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SlianoaAttendanceRecord record);
}