package com.slianOAsys.dao;

import com.slianOAsys.model.SlianoaAttendance;
import com.slianOAsys.model.SlianoaAttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlianoaAttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int countByExample(SlianoaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int deleteByExample(SlianoaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int insert(SlianoaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int insertSelective(SlianoaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    List<SlianoaAttendance> selectByExample(SlianoaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    SlianoaAttendance selectByPrimaryKey(Integer attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SlianoaAttendance record, @Param("example") SlianoaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SlianoaAttendance record, @Param("example") SlianoaAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SlianoaAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SlianoaAttendance record);
}