package com.slianOAsys.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.slianOAsys.model.SysEmployee;
import com.slianOAsys.model.SysEmployeeExample;

public interface SysEmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int countByExample(SysEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int deleteByExample(SysEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int deleteByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int insert(SysEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int insertSelective(SysEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	List<SysEmployee> selectByExample(SysEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	SysEmployee selectByPrimaryKey(Integer employeeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysEmployee record,
			@Param("example") SysEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int updateByExample(@Param("record") SysEmployee record,
			@Param("example") SysEmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int updateByPrimaryKeySelective(SysEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_employee
	 * @mbggenerated  Fri Dec 23 08:06:11 CST 2016
	 */
	int updateByPrimaryKey(SysEmployee record);
}