package com.slianOAsys.dao;

import com.slianOAsys.model.SysRoles;
import com.slianOAsys.model.SysRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int countByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int insert(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int insertSelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    List<SysRoles> selectByExample(SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    SysRoles selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRoles record, @Param("example") SysRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoles record);
}