package com.slianOAsys.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.slianOAsys.model.SysUsersRoles;
import com.slianOAsys.model.SysUsersRolesExample;

public interface SysUsersRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int countByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insert(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int insertSelective(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    List<SysUsersRoles> selectByExample(SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    SysUsersRoles selectByPrimaryKey(Integer urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUsersRoles record, @Param("example") SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUsersRoles record, @Param("example") SysUsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_users_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUsersRoles record);
}