package com.slianOAsys.model;

import java.util.Date;

public class SlianoaClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.sign_address
     *
     * @mbggenerated
     */
    private String signAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.longitude
     *
     * @mbggenerated
     */
    private Float longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.latitude
     *
     * @mbggenerated
     */
    private Float latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.scope
     *
     * @mbggenerated
     */
    private Integer scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.signin_start
     *
     * @mbggenerated
     */
    private Date signinStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.signin_end
     *
     * @mbggenerated
     */
    private Date signinEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.signoff_start
     *
     * @mbggenerated
     */
    private Date signoffStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.signoff_end
     *
     * @mbggenerated
     */
    private Date signoffEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.class_status
     *
     * @mbggenerated
     */
    private String classStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_monday
     *
     * @mbggenerated
     */
    private Integer isMonday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_tuesday
     *
     * @mbggenerated
     */
    private Integer isTuesday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_wednesday
     *
     * @mbggenerated
     */
    private Integer isWednesday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_thursday
     *
     * @mbggenerated
     */
    private Integer isThursday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_friday
     *
     * @mbggenerated
     */
    private Integer isFriday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_saturday
     *
     * @mbggenerated
     */
    private Integer isSaturday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class.is_sunday
     *
     * @mbggenerated
     */
    private Integer isSunday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.class_id
     *
     * @return the value of slianoa_class.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.class_id
     *
     * @param classId the value for slianoa_class.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.class_name
     *
     * @return the value of slianoa_class.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.class_name
     *
     * @param className the value for slianoa_class.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.start_time
     *
     * @return the value of slianoa_class.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.start_time
     *
     * @param startTime the value for slianoa_class.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.end_time
     *
     * @return the value of slianoa_class.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.end_time
     *
     * @param endTime the value for slianoa_class.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.description
     *
     * @return the value of slianoa_class.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.description
     *
     * @param description the value for slianoa_class.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.sign_address
     *
     * @return the value of slianoa_class.sign_address
     *
     * @mbggenerated
     */
    public String getSignAddress() {
        return signAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.sign_address
     *
     * @param signAddress the value for slianoa_class.sign_address
     *
     * @mbggenerated
     */
    public void setSignAddress(String signAddress) {
        this.signAddress = signAddress == null ? null : signAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.longitude
     *
     * @return the value of slianoa_class.longitude
     *
     * @mbggenerated
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.longitude
     *
     * @param longitude the value for slianoa_class.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.latitude
     *
     * @return the value of slianoa_class.latitude
     *
     * @mbggenerated
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.latitude
     *
     * @param latitude the value for slianoa_class.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.scope
     *
     * @return the value of slianoa_class.scope
     *
     * @mbggenerated
     */
    public Integer getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.scope
     *
     * @param scope the value for slianoa_class.scope
     *
     * @mbggenerated
     */
    public void setScope(Integer scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.signin_start
     *
     * @return the value of slianoa_class.signin_start
     *
     * @mbggenerated
     */
    public Date getSigninStart() {
        return signinStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.signin_start
     *
     * @param signinStart the value for slianoa_class.signin_start
     *
     * @mbggenerated
     */
    public void setSigninStart(Date signinStart) {
        this.signinStart = signinStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.signin_end
     *
     * @return the value of slianoa_class.signin_end
     *
     * @mbggenerated
     */
    public Date getSigninEnd() {
        return signinEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.signin_end
     *
     * @param signinEnd the value for slianoa_class.signin_end
     *
     * @mbggenerated
     */
    public void setSigninEnd(Date signinEnd) {
        this.signinEnd = signinEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.signoff_start
     *
     * @return the value of slianoa_class.signoff_start
     *
     * @mbggenerated
     */
    public Date getSignoffStart() {
        return signoffStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.signoff_start
     *
     * @param signoffStart the value for slianoa_class.signoff_start
     *
     * @mbggenerated
     */
    public void setSignoffStart(Date signoffStart) {
        this.signoffStart = signoffStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.signoff_end
     *
     * @return the value of slianoa_class.signoff_end
     *
     * @mbggenerated
     */
    public Date getSignoffEnd() {
        return signoffEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.signoff_end
     *
     * @param signoffEnd the value for slianoa_class.signoff_end
     *
     * @mbggenerated
     */
    public void setSignoffEnd(Date signoffEnd) {
        this.signoffEnd = signoffEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.class_status
     *
     * @return the value of slianoa_class.class_status
     *
     * @mbggenerated
     */
    public String getClassStatus() {
        return classStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.class_status
     *
     * @param classStatus the value for slianoa_class.class_status
     *
     * @mbggenerated
     */
    public void setClassStatus(String classStatus) {
        this.classStatus = classStatus == null ? null : classStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.create_time
     *
     * @return the value of slianoa_class.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.create_time
     *
     * @param createTime the value for slianoa_class.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_monday
     *
     * @return the value of slianoa_class.is_monday
     *
     * @mbggenerated
     */
    public Integer getIsMonday() {
        return isMonday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_monday
     *
     * @param isMonday the value for slianoa_class.is_monday
     *
     * @mbggenerated
     */
    public void setIsMonday(Integer isMonday) {
        this.isMonday = isMonday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_tuesday
     *
     * @return the value of slianoa_class.is_tuesday
     *
     * @mbggenerated
     */
    public Integer getIsTuesday() {
        return isTuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_tuesday
     *
     * @param isTuesday the value for slianoa_class.is_tuesday
     *
     * @mbggenerated
     */
    public void setIsTuesday(Integer isTuesday) {
        this.isTuesday = isTuesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_wednesday
     *
     * @return the value of slianoa_class.is_wednesday
     *
     * @mbggenerated
     */
    public Integer getIsWednesday() {
        return isWednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_wednesday
     *
     * @param isWednesday the value for slianoa_class.is_wednesday
     *
     * @mbggenerated
     */
    public void setIsWednesday(Integer isWednesday) {
        this.isWednesday = isWednesday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_thursday
     *
     * @return the value of slianoa_class.is_thursday
     *
     * @mbggenerated
     */
    public Integer getIsThursday() {
        return isThursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_thursday
     *
     * @param isThursday the value for slianoa_class.is_thursday
     *
     * @mbggenerated
     */
    public void setIsThursday(Integer isThursday) {
        this.isThursday = isThursday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_friday
     *
     * @return the value of slianoa_class.is_friday
     *
     * @mbggenerated
     */
    public Integer getIsFriday() {
        return isFriday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_friday
     *
     * @param isFriday the value for slianoa_class.is_friday
     *
     * @mbggenerated
     */
    public void setIsFriday(Integer isFriday) {
        this.isFriday = isFriday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_saturday
     *
     * @return the value of slianoa_class.is_saturday
     *
     * @mbggenerated
     */
    public Integer getIsSaturday() {
        return isSaturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_saturday
     *
     * @param isSaturday the value for slianoa_class.is_saturday
     *
     * @mbggenerated
     */
    public void setIsSaturday(Integer isSaturday) {
        this.isSaturday = isSaturday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class.is_sunday
     *
     * @return the value of slianoa_class.is_sunday
     *
     * @mbggenerated
     */
    public Integer getIsSunday() {
        return isSunday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class.is_sunday
     *
     * @param isSunday the value for slianoa_class.is_sunday
     *
     * @mbggenerated
     */
    public void setIsSunday(Integer isSunday) {
        this.isSunday = isSunday;
    }
}