package com.slianOAsys.model;

public class SlianoaAttendanceRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_attendance_record.record_id
     *
     * @mbggenerated
     */
    private Integer recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_attendance_record.record_signtime
     *
     * @mbggenerated
     */
    private String recordSigntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_attendance_record.record_signaddress
     *
     * @mbggenerated
     */
    private String recordSignaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_attendance_record.record_signstatus
     *
     * @mbggenerated
     */
    private String recordSignstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_attendance_record.record_wechat
     *
     * @mbggenerated
     */
    private String recordWechat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_attendance_record.record_id
     *
     * @return the value of slianoa_attendance_record.record_id
     *
     * @mbggenerated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_attendance_record.record_id
     *
     * @param recordId the value for slianoa_attendance_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_attendance_record.record_signtime
     *
     * @return the value of slianoa_attendance_record.record_signtime
     *
     * @mbggenerated
     */
    public String getRecordSigntime() {
        return recordSigntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_attendance_record.record_signtime
     *
     * @param recordSigntime the value for slianoa_attendance_record.record_signtime
     *
     * @mbggenerated
     */
    public void setRecordSigntime(String recordSigntime) {
        this.recordSigntime = recordSigntime == null ? null : recordSigntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_attendance_record.record_signaddress
     *
     * @return the value of slianoa_attendance_record.record_signaddress
     *
     * @mbggenerated
     */
    public String getRecordSignaddress() {
        return recordSignaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_attendance_record.record_signaddress
     *
     * @param recordSignaddress the value for slianoa_attendance_record.record_signaddress
     *
     * @mbggenerated
     */
    public void setRecordSignaddress(String recordSignaddress) {
        this.recordSignaddress = recordSignaddress == null ? null : recordSignaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_attendance_record.record_signstatus
     *
     * @return the value of slianoa_attendance_record.record_signstatus
     *
     * @mbggenerated
     */
    public String getRecordSignstatus() {
        return recordSignstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_attendance_record.record_signstatus
     *
     * @param recordSignstatus the value for slianoa_attendance_record.record_signstatus
     *
     * @mbggenerated
     */
    public void setRecordSignstatus(String recordSignstatus) {
        this.recordSignstatus = recordSignstatus == null ? null : recordSignstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_attendance_record.record_wechat
     *
     * @return the value of slianoa_attendance_record.record_wechat
     *
     * @mbggenerated
     */
    public String getRecordWechat() {
        return recordWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_attendance_record.record_wechat
     *
     * @param recordWechat the value for slianoa_attendance_record.record_wechat
     *
     * @mbggenerated
     */
    public void setRecordWechat(String recordWechat) {
        this.recordWechat = recordWechat == null ? null : recordWechat.trim();
    }
}