package com.slianOAsys.model;

public class SlianoaClassEmployee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class_employee.class_employee_id
     *
     * @mbggenerated
     */
    private Integer classEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class_employee.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class_employee.employee_id
     *
     * @mbggenerated
     */
    private Integer employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_class_employee.depart_id
     *
     * @mbggenerated
     */
    private Integer departId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class_employee.class_employee_id
     *
     * @return the value of slianoa_class_employee.class_employee_id
     *
     * @mbggenerated
     */
    public Integer getClassEmployeeId() {
        return classEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class_employee.class_employee_id
     *
     * @param classEmployeeId the value for slianoa_class_employee.class_employee_id
     *
     * @mbggenerated
     */
    public void setClassEmployeeId(Integer classEmployeeId) {
        this.classEmployeeId = classEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class_employee.class_id
     *
     * @return the value of slianoa_class_employee.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class_employee.class_id
     *
     * @param classId the value for slianoa_class_employee.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class_employee.employee_id
     *
     * @return the value of slianoa_class_employee.employee_id
     *
     * @mbggenerated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class_employee.employee_id
     *
     * @param employeeId the value for slianoa_class_employee.employee_id
     *
     * @mbggenerated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_class_employee.depart_id
     *
     * @return the value of slianoa_class_employee.depart_id
     *
     * @mbggenerated
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_class_employee.depart_id
     *
     * @param departId the value for slianoa_class_employee.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }
}