package com.slianOAsys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SlianoaEmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public SlianoaEmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("employee_id is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("employee_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(Integer value) {
            addCriterion("employee_id =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(Integer value) {
            addCriterion("employee_id <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(Integer value) {
            addCriterion("employee_id >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_id >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(Integer value) {
            addCriterion("employee_id <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(Integer value) {
            addCriterion("employee_id <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<Integer> values) {
            addCriterion("employee_id in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<Integer> values) {
            addCriterion("employee_id not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(Integer value1, Integer value2) {
            addCriterion("employee_id between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_id not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNull() {
            addCriterion("depart_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNotNull() {
            addCriterion("depart_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartIdEqualTo(Integer value) {
            addCriterion("depart_id =", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotEqualTo(Integer value) {
            addCriterion("depart_id <>", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThan(Integer value) {
            addCriterion("depart_id >", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("depart_id >=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThan(Integer value) {
            addCriterion("depart_id <", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThanOrEqualTo(Integer value) {
            addCriterion("depart_id <=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdIn(List<Integer> values) {
            addCriterion("depart_id in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotIn(List<Integer> values) {
            addCriterion("depart_id not in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdBetween(Integer value1, Integer value2) {
            addCriterion("depart_id between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotBetween(Integer value1, Integer value2) {
            addCriterion("depart_id not between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNull() {
            addCriterion("employee_name is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNotNull() {
            addCriterion("employee_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameEqualTo(String value) {
            addCriterion("employee_name =", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotEqualTo(String value) {
            addCriterion("employee_name <>", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThan(String value) {
            addCriterion("employee_name >", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("employee_name >=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThan(String value) {
            addCriterion("employee_name <", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("employee_name <=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLike(String value) {
            addCriterion("employee_name like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotLike(String value) {
            addCriterion("employee_name not like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIn(List<String> values) {
            addCriterion("employee_name in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotIn(List<String> values) {
            addCriterion("employee_name not in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameBetween(String value1, String value2) {
            addCriterion("employee_name between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("employee_name not between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderIsNull() {
            addCriterion("employee_gender is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderIsNotNull() {
            addCriterion("employee_gender is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderEqualTo(String value) {
            addCriterion("employee_gender =", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderNotEqualTo(String value) {
            addCriterion("employee_gender <>", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderGreaterThan(String value) {
            addCriterion("employee_gender >", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderGreaterThanOrEqualTo(String value) {
            addCriterion("employee_gender >=", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderLessThan(String value) {
            addCriterion("employee_gender <", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderLessThanOrEqualTo(String value) {
            addCriterion("employee_gender <=", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderLike(String value) {
            addCriterion("employee_gender like", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderNotLike(String value) {
            addCriterion("employee_gender not like", value, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderIn(List<String> values) {
            addCriterion("employee_gender in", values, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderNotIn(List<String> values) {
            addCriterion("employee_gender not in", values, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderBetween(String value1, String value2) {
            addCriterion("employee_gender between", value1, value2, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeeGenderNotBetween(String value1, String value2) {
            addCriterion("employee_gender not between", value1, value2, "employeeGender");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIsNull() {
            addCriterion("employee_position is null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIsNotNull() {
            addCriterion("employee_position is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionEqualTo(String value) {
            addCriterion("employee_position =", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotEqualTo(String value) {
            addCriterion("employee_position <>", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionGreaterThan(String value) {
            addCriterion("employee_position >", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionGreaterThanOrEqualTo(String value) {
            addCriterion("employee_position >=", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionLessThan(String value) {
            addCriterion("employee_position <", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionLessThanOrEqualTo(String value) {
            addCriterion("employee_position <=", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionLike(String value) {
            addCriterion("employee_position like", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotLike(String value) {
            addCriterion("employee_position not like", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIn(List<String> values) {
            addCriterion("employee_position in", values, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotIn(List<String> values) {
            addCriterion("employee_position not in", values, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionBetween(String value1, String value2) {
            addCriterion("employee_position between", value1, value2, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotBetween(String value1, String value2) {
            addCriterion("employee_position not between", value1, value2, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeIsNull() {
            addCriterion("employee_age is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeIsNotNull() {
            addCriterion("employee_age is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeEqualTo(Integer value) {
            addCriterion("employee_age =", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeNotEqualTo(Integer value) {
            addCriterion("employee_age <>", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeGreaterThan(Integer value) {
            addCriterion("employee_age >", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_age >=", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeLessThan(Integer value) {
            addCriterion("employee_age <", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeLessThanOrEqualTo(Integer value) {
            addCriterion("employee_age <=", value, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeIn(List<Integer> values) {
            addCriterion("employee_age in", values, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeNotIn(List<Integer> values) {
            addCriterion("employee_age not in", values, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeBetween(Integer value1, Integer value2) {
            addCriterion("employee_age between", value1, value2, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeeAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_age not between", value1, value2, "employeeAge");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberIsNull() {
            addCriterion("employee_phone_number is null");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberIsNotNull() {
            addCriterion("employee_phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberEqualTo(String value) {
            addCriterion("employee_phone_number =", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberNotEqualTo(String value) {
            addCriterion("employee_phone_number <>", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberGreaterThan(String value) {
            addCriterion("employee_phone_number >", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("employee_phone_number >=", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberLessThan(String value) {
            addCriterion("employee_phone_number <", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("employee_phone_number <=", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberLike(String value) {
            addCriterion("employee_phone_number like", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberNotLike(String value) {
            addCriterion("employee_phone_number not like", value, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberIn(List<String> values) {
            addCriterion("employee_phone_number in", values, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberNotIn(List<String> values) {
            addCriterion("employee_phone_number not in", values, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberBetween(String value1, String value2) {
            addCriterion("employee_phone_number between", value1, value2, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeePhoneNumberNotBetween(String value1, String value2) {
            addCriterion("employee_phone_number not between", value1, value2, "employeePhoneNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIsNull() {
            addCriterion("employee_status is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIsNotNull() {
            addCriterion("employee_status is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusEqualTo(String value) {
            addCriterion("employee_status =", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotEqualTo(String value) {
            addCriterion("employee_status <>", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusGreaterThan(String value) {
            addCriterion("employee_status >", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("employee_status >=", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusLessThan(String value) {
            addCriterion("employee_status <", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusLessThanOrEqualTo(String value) {
            addCriterion("employee_status <=", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusLike(String value) {
            addCriterion("employee_status like", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotLike(String value) {
            addCriterion("employee_status not like", value, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusIn(List<String> values) {
            addCriterion("employee_status in", values, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotIn(List<String> values) {
            addCriterion("employee_status not in", values, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusBetween(String value1, String value2) {
            addCriterion("employee_status between", value1, value2, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeStatusNotBetween(String value1, String value2) {
            addCriterion("employee_status not between", value1, value2, "employeeStatus");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardIsNull() {
            addCriterion("employee_Idcard is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardIsNotNull() {
            addCriterion("employee_Idcard is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardEqualTo(String value) {
            addCriterion("employee_Idcard =", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardNotEqualTo(String value) {
            addCriterion("employee_Idcard <>", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardGreaterThan(String value) {
            addCriterion("employee_Idcard >", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("employee_Idcard >=", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardLessThan(String value) {
            addCriterion("employee_Idcard <", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardLessThanOrEqualTo(String value) {
            addCriterion("employee_Idcard <=", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardLike(String value) {
            addCriterion("employee_Idcard like", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardNotLike(String value) {
            addCriterion("employee_Idcard not like", value, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardIn(List<String> values) {
            addCriterion("employee_Idcard in", values, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardNotIn(List<String> values) {
            addCriterion("employee_Idcard not in", values, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardBetween(String value1, String value2) {
            addCriterion("employee_Idcard between", value1, value2, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdcardNotBetween(String value1, String value2) {
            addCriterion("employee_Idcard not between", value1, value2, "employeeIdcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardIsNull() {
            addCriterion("employee_bankcard is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardIsNotNull() {
            addCriterion("employee_bankcard is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardEqualTo(String value) {
            addCriterion("employee_bankcard =", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardNotEqualTo(String value) {
            addCriterion("employee_bankcard <>", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardGreaterThan(String value) {
            addCriterion("employee_bankcard >", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardGreaterThanOrEqualTo(String value) {
            addCriterion("employee_bankcard >=", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardLessThan(String value) {
            addCriterion("employee_bankcard <", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardLessThanOrEqualTo(String value) {
            addCriterion("employee_bankcard <=", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardLike(String value) {
            addCriterion("employee_bankcard like", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardNotLike(String value) {
            addCriterion("employee_bankcard not like", value, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardIn(List<String> values) {
            addCriterion("employee_bankcard in", values, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardNotIn(List<String> values) {
            addCriterion("employee_bankcard not in", values, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardBetween(String value1, String value2) {
            addCriterion("employee_bankcard between", value1, value2, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeBankcardNotBetween(String value1, String value2) {
            addCriterion("employee_bankcard not between", value1, value2, "employeeBankcard");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankIsNull() {
            addCriterion("employee_openbank is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankIsNotNull() {
            addCriterion("employee_openbank is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankEqualTo(String value) {
            addCriterion("employee_openbank =", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankNotEqualTo(String value) {
            addCriterion("employee_openbank <>", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankGreaterThan(String value) {
            addCriterion("employee_openbank >", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankGreaterThanOrEqualTo(String value) {
            addCriterion("employee_openbank >=", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankLessThan(String value) {
            addCriterion("employee_openbank <", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankLessThanOrEqualTo(String value) {
            addCriterion("employee_openbank <=", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankLike(String value) {
            addCriterion("employee_openbank like", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankNotLike(String value) {
            addCriterion("employee_openbank not like", value, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankIn(List<String> values) {
            addCriterion("employee_openbank in", values, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankNotIn(List<String> values) {
            addCriterion("employee_openbank not in", values, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankBetween(String value1, String value2) {
            addCriterion("employee_openbank between", value1, value2, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEmployeeOpenbankNotBetween(String value1, String value2) {
            addCriterion("employee_openbank not between", value1, value2, "employeeOpenbank");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNull() {
            addCriterion("entrytime is null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIsNotNull() {
            addCriterion("entrytime is not null");
            return (Criteria) this;
        }

        public Criteria andEntrytimeEqualTo(Date value) {
            addCriterionForJDBCDate("entrytime =", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("entrytime <>", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThan(Date value) {
            addCriterionForJDBCDate("entrytime >", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("entrytime >=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThan(Date value) {
            addCriterionForJDBCDate("entrytime <", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("entrytime <=", value, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeIn(List<Date> values) {
            addCriterionForJDBCDate("entrytime in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("entrytime not in", values, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("entrytime between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andEntrytimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("entrytime not between", value1, value2, "entrytime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeIsNull() {
            addCriterion("leavetime is null");
            return (Criteria) this;
        }

        public Criteria andLeavetimeIsNotNull() {
            addCriterion("leavetime is not null");
            return (Criteria) this;
        }

        public Criteria andLeavetimeEqualTo(Date value) {
            addCriterionForJDBCDate("leavetime =", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("leavetime <>", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("leavetime >", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("leavetime >=", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeLessThan(Date value) {
            addCriterionForJDBCDate("leavetime <", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("leavetime <=", value, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeIn(List<Date> values) {
            addCriterionForJDBCDate("leavetime in", values, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("leavetime not in", values, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("leavetime between", value1, value2, "leavetime");
            return (Criteria) this;
        }

        public Criteria andLeavetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("leavetime not between", value1, value2, "leavetime");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolIsNull() {
            addCriterion("employee_Undergraduate_school is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolIsNotNull() {
            addCriterion("employee_Undergraduate_school is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolEqualTo(String value) {
            addCriterion("employee_Undergraduate_school =", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolNotEqualTo(String value) {
            addCriterion("employee_Undergraduate_school <>", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolGreaterThan(String value) {
            addCriterion("employee_Undergraduate_school >", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("employee_Undergraduate_school >=", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolLessThan(String value) {
            addCriterion("employee_Undergraduate_school <", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolLessThanOrEqualTo(String value) {
            addCriterion("employee_Undergraduate_school <=", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolLike(String value) {
            addCriterion("employee_Undergraduate_school like", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolNotLike(String value) {
            addCriterion("employee_Undergraduate_school not like", value, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolIn(List<String> values) {
            addCriterion("employee_Undergraduate_school in", values, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolNotIn(List<String> values) {
            addCriterion("employee_Undergraduate_school not in", values, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolBetween(String value1, String value2) {
            addCriterion("employee_Undergraduate_school between", value1, value2, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeUndergraduateSchoolNotBetween(String value1, String value2) {
            addCriterion("employee_Undergraduate_school not between", value1, value2, "employeeUndergraduateSchool");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundIsNull() {
            addCriterion("employee_education_background is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundIsNotNull() {
            addCriterion("employee_education_background is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundEqualTo(String value) {
            addCriterion("employee_education_background =", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundNotEqualTo(String value) {
            addCriterion("employee_education_background <>", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundGreaterThan(String value) {
            addCriterion("employee_education_background >", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("employee_education_background >=", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundLessThan(String value) {
            addCriterion("employee_education_background <", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundLessThanOrEqualTo(String value) {
            addCriterion("employee_education_background <=", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundLike(String value) {
            addCriterion("employee_education_background like", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundNotLike(String value) {
            addCriterion("employee_education_background not like", value, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundIn(List<String> values) {
            addCriterion("employee_education_background in", values, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundNotIn(List<String> values) {
            addCriterion("employee_education_background not in", values, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundBetween(String value1, String value2) {
            addCriterion("employee_education_background between", value1, value2, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeEducationBackgroundNotBetween(String value1, String value2) {
            addCriterion("employee_education_background not between", value1, value2, "employeeEducationBackground");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeIsNull() {
            addCriterion("employee_grade is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeIsNotNull() {
            addCriterion("employee_grade is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeEqualTo(String value) {
            addCriterion("employee_grade =", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeNotEqualTo(String value) {
            addCriterion("employee_grade <>", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeGreaterThan(String value) {
            addCriterion("employee_grade >", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeGreaterThanOrEqualTo(String value) {
            addCriterion("employee_grade >=", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeLessThan(String value) {
            addCriterion("employee_grade <", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeLessThanOrEqualTo(String value) {
            addCriterion("employee_grade <=", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeLike(String value) {
            addCriterion("employee_grade like", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeNotLike(String value) {
            addCriterion("employee_grade not like", value, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeIn(List<String> values) {
            addCriterion("employee_grade in", values, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeNotIn(List<String> values) {
            addCriterion("employee_grade not in", values, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeBetween(String value1, String value2) {
            addCriterion("employee_grade between", value1, value2, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeGradeNotBetween(String value1, String value2) {
            addCriterion("employee_grade not between", value1, value2, "employeeGrade");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorIsNull() {
            addCriterion("employee_major is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorIsNotNull() {
            addCriterion("employee_major is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorEqualTo(String value) {
            addCriterion("employee_major =", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorNotEqualTo(String value) {
            addCriterion("employee_major <>", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorGreaterThan(String value) {
            addCriterion("employee_major >", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorGreaterThanOrEqualTo(String value) {
            addCriterion("employee_major >=", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorLessThan(String value) {
            addCriterion("employee_major <", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorLessThanOrEqualTo(String value) {
            addCriterion("employee_major <=", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorLike(String value) {
            addCriterion("employee_major like", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorNotLike(String value) {
            addCriterion("employee_major not like", value, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorIn(List<String> values) {
            addCriterion("employee_major in", values, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorNotIn(List<String> values) {
            addCriterion("employee_major not in", values, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorBetween(String value1, String value2) {
            addCriterion("employee_major between", value1, value2, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeMajorNotBetween(String value1, String value2) {
            addCriterion("employee_major not between", value1, value2, "employeeMajor");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIsNull() {
            addCriterion("employee_email is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIsNotNull() {
            addCriterion("employee_email is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailEqualTo(String value) {
            addCriterion("employee_email =", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotEqualTo(String value) {
            addCriterion("employee_email <>", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailGreaterThan(String value) {
            addCriterion("employee_email >", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("employee_email >=", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLessThan(String value) {
            addCriterion("employee_email <", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLessThanOrEqualTo(String value) {
            addCriterion("employee_email <=", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailLike(String value) {
            addCriterion("employee_email like", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotLike(String value) {
            addCriterion("employee_email not like", value, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailIn(List<String> values) {
            addCriterion("employee_email in", values, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotIn(List<String> values) {
            addCriterion("employee_email not in", values, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailBetween(String value1, String value2) {
            addCriterion("employee_email between", value1, value2, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeEmailNotBetween(String value1, String value2) {
            addCriterion("employee_email not between", value1, value2, "employeeEmail");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatIsNull() {
            addCriterion("employee_wechat is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatIsNotNull() {
            addCriterion("employee_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatEqualTo(String value) {
            addCriterion("employee_wechat =", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatNotEqualTo(String value) {
            addCriterion("employee_wechat <>", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatGreaterThan(String value) {
            addCriterion("employee_wechat >", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatGreaterThanOrEqualTo(String value) {
            addCriterion("employee_wechat >=", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatLessThan(String value) {
            addCriterion("employee_wechat <", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatLessThanOrEqualTo(String value) {
            addCriterion("employee_wechat <=", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatLike(String value) {
            addCriterion("employee_wechat like", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatNotLike(String value) {
            addCriterion("employee_wechat not like", value, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatIn(List<String> values) {
            addCriterion("employee_wechat in", values, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatNotIn(List<String> values) {
            addCriterion("employee_wechat not in", values, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatBetween(String value1, String value2) {
            addCriterion("employee_wechat between", value1, value2, "employeeWechat");
            return (Criteria) this;
        }

        public Criteria andEmployeeWechatNotBetween(String value1, String value2) {
            addCriterion("employee_wechat not between", value1, value2, "employeeWechat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_employee
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_employee
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}