package com.slianOAsys.model;

import java.util.Date;

public class slianoaUnattendDays {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.unattend_days_id
     *
     * @mbggenerated
     */
    private Integer unattendDaysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.reason
     *
     * @mbggenerated
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.add_or_delete
     *
     * @mbggenerated
     */
    private String addOrDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.is_pastdue
     *
     * @mbggenerated
     */
    private Integer isPastdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.amend_time
     *
     * @mbggenerated
     */
    private Date amendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.amender
     *
     * @mbggenerated
     */
    private String amender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slianoa_unattend_days.class_id
     *
     * @mbggenerated
     */
    private Integer classId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.unattend_days_id
     *
     * @return the value of slianoa_unattend_days.unattend_days_id
     *
     * @mbggenerated
     */
    public Integer getUnattendDaysId() {
        return unattendDaysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.unattend_days_id
     *
     * @param unattendDaysId the value for slianoa_unattend_days.unattend_days_id
     *
     * @mbggenerated
     */
    public void setUnattendDaysId(Integer unattendDaysId) {
        this.unattendDaysId = unattendDaysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.reason
     *
     * @return the value of slianoa_unattend_days.reason
     *
     * @mbggenerated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.reason
     *
     * @param reason the value for slianoa_unattend_days.reason
     *
     * @mbggenerated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.add_or_delete
     *
     * @return the value of slianoa_unattend_days.add_or_delete
     *
     * @mbggenerated
     */
    public String getAddOrDelete() {
        return addOrDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.add_or_delete
     *
     * @param addOrDelete the value for slianoa_unattend_days.add_or_delete
     *
     * @mbggenerated
     */
    public void setAddOrDelete(String addOrDelete) {
        this.addOrDelete = addOrDelete == null ? null : addOrDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.date
     *
     * @return the value of slianoa_unattend_days.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.date
     *
     * @param date the value for slianoa_unattend_days.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.is_pastdue
     *
     * @return the value of slianoa_unattend_days.is_pastdue
     *
     * @mbggenerated
     */
    public Integer getIsPastdue() {
        return isPastdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.is_pastdue
     *
     * @param isPastdue the value for slianoa_unattend_days.is_pastdue
     *
     * @mbggenerated
     */
    public void setIsPastdue(Integer isPastdue) {
        this.isPastdue = isPastdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.remark
     *
     * @return the value of slianoa_unattend_days.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.remark
     *
     * @param remark the value for slianoa_unattend_days.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.amend_time
     *
     * @return the value of slianoa_unattend_days.amend_time
     *
     * @mbggenerated
     */
    public Date getAmendTime() {
        return amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.amend_time
     *
     * @param amendTime the value for slianoa_unattend_days.amend_time
     *
     * @mbggenerated
     */
    public void setAmendTime(Date amendTime) {
        this.amendTime = amendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.amender
     *
     * @return the value of slianoa_unattend_days.amender
     *
     * @mbggenerated
     */
    public String getAmender() {
        return amender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.amender
     *
     * @param amender the value for slianoa_unattend_days.amender
     *
     * @mbggenerated
     */
    public void setAmender(String amender) {
        this.amender = amender == null ? null : amender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.create_time
     *
     * @return the value of slianoa_unattend_days.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.create_time
     *
     * @param createTime the value for slianoa_unattend_days.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.creator
     *
     * @return the value of slianoa_unattend_days.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.creator
     *
     * @param creator the value for slianoa_unattend_days.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slianoa_unattend_days.class_id
     *
     * @return the value of slianoa_unattend_days.class_id
     *
     * @mbggenerated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slianoa_unattend_days.class_id
     *
     * @param classId the value for slianoa_unattend_days.class_id
     *
     * @mbggenerated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
}