package com.slianOAsys.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import com.slianOAsys.page.Page;

public class SlianoaClassExample {
	protected Page page;
	public void setPage(Page page) {
	        this.page=page;
	    }

	    public Page getPage() {
	        return page;
	    }
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public SlianoaClassExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Integer value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Integer value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Integer value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Integer value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Integer> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Integer> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Integer value1, Integer value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("class_name is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("class_name is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("class_name =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("class_name <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("class_name >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("class_name >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("class_name <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("class_name <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("class_name like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("class_name not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("class_name in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("class_name not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("class_name between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("class_name not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterionForJDBCTime("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterionForJDBCTime("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterionForJDBCTime("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCTime("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCTime("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterionForJDBCTime("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andSignAddressIsNull() {
            addCriterion("sign_address is null");
            return (Criteria) this;
        }

        public Criteria andSignAddressIsNotNull() {
            addCriterion("sign_address is not null");
            return (Criteria) this;
        }

        public Criteria andSignAddressEqualTo(String value) {
            addCriterion("sign_address =", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressNotEqualTo(String value) {
            addCriterion("sign_address <>", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressGreaterThan(String value) {
            addCriterion("sign_address >", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sign_address >=", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressLessThan(String value) {
            addCriterion("sign_address <", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressLessThanOrEqualTo(String value) {
            addCriterion("sign_address <=", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressLike(String value) {
            addCriterion("sign_address like", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressNotLike(String value) {
            addCriterion("sign_address not like", value, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressIn(List<String> values) {
            addCriterion("sign_address in", values, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressNotIn(List<String> values) {
            addCriterion("sign_address not in", values, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressBetween(String value1, String value2) {
            addCriterion("sign_address between", value1, value2, "signAddress");
            return (Criteria) this;
        }

        public Criteria andSignAddressNotBetween(String value1, String value2) {
            addCriterion("sign_address not between", value1, value2, "signAddress");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Float value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Float value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Float value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Float value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Float value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Float> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Float> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Float value1, Float value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Float value1, Float value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Float value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Float value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Float value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Float value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Float value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Float> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Float> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Float value1, Float value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Float value1, Float value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(Integer value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(Integer value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(Integer value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(Integer value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(Integer value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(Integer value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<Integer> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<Integer> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(Integer value1, Integer value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(Integer value1, Integer value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andSigninStartIsNull() {
            addCriterion("signin_start is null");
            return (Criteria) this;
        }

        public Criteria andSigninStartIsNotNull() {
            addCriterion("signin_start is not null");
            return (Criteria) this;
        }

        public Criteria andSigninStartEqualTo(Date value) {
            addCriterionForJDBCTime("signin_start =", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartNotEqualTo(Date value) {
            addCriterionForJDBCTime("signin_start <>", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartGreaterThan(Date value) {
            addCriterionForJDBCTime("signin_start >", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signin_start >=", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartLessThan(Date value) {
            addCriterionForJDBCTime("signin_start <", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signin_start <=", value, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartIn(List<Date> values) {
            addCriterionForJDBCTime("signin_start in", values, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartNotIn(List<Date> values) {
            addCriterionForJDBCTime("signin_start not in", values, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signin_start between", value1, value2, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signin_start not between", value1, value2, "signinStart");
            return (Criteria) this;
        }

        public Criteria andSigninEndIsNull() {
            addCriterion("signin_end is null");
            return (Criteria) this;
        }

        public Criteria andSigninEndIsNotNull() {
            addCriterion("signin_end is not null");
            return (Criteria) this;
        }

        public Criteria andSigninEndEqualTo(Date value) {
            addCriterionForJDBCTime("signin_end =", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndNotEqualTo(Date value) {
            addCriterionForJDBCTime("signin_end <>", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndGreaterThan(Date value) {
            addCriterionForJDBCTime("signin_end >", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signin_end >=", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndLessThan(Date value) {
            addCriterionForJDBCTime("signin_end <", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signin_end <=", value, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndIn(List<Date> values) {
            addCriterionForJDBCTime("signin_end in", values, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndNotIn(List<Date> values) {
            addCriterionForJDBCTime("signin_end not in", values, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signin_end between", value1, value2, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSigninEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signin_end not between", value1, value2, "signinEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffStartIsNull() {
            addCriterion("signoff_start is null");
            return (Criteria) this;
        }

        public Criteria andSignoffStartIsNotNull() {
            addCriterion("signoff_start is not null");
            return (Criteria) this;
        }

        public Criteria andSignoffStartEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_start =", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartNotEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_start <>", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartGreaterThan(Date value) {
            addCriterionForJDBCTime("signoff_start >", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_start >=", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartLessThan(Date value) {
            addCriterionForJDBCTime("signoff_start <", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_start <=", value, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartIn(List<Date> values) {
            addCriterionForJDBCTime("signoff_start in", values, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartNotIn(List<Date> values) {
            addCriterionForJDBCTime("signoff_start not in", values, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signoff_start between", value1, value2, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signoff_start not between", value1, value2, "signoffStart");
            return (Criteria) this;
        }

        public Criteria andSignoffEndIsNull() {
            addCriterion("signoff_end is null");
            return (Criteria) this;
        }

        public Criteria andSignoffEndIsNotNull() {
            addCriterion("signoff_end is not null");
            return (Criteria) this;
        }

        public Criteria andSignoffEndEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_end =", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndNotEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_end <>", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndGreaterThan(Date value) {
            addCriterionForJDBCTime("signoff_end >", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_end >=", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndLessThan(Date value) {
            addCriterionForJDBCTime("signoff_end <", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("signoff_end <=", value, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndIn(List<Date> values) {
            addCriterionForJDBCTime("signoff_end in", values, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndNotIn(List<Date> values) {
            addCriterionForJDBCTime("signoff_end not in", values, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signoff_end between", value1, value2, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andSignoffEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("signoff_end not between", value1, value2, "signoffEnd");
            return (Criteria) this;
        }

        public Criteria andClassStatusIsNull() {
            addCriterion("class_status is null");
            return (Criteria) this;
        }

        public Criteria andClassStatusIsNotNull() {
            addCriterion("class_status is not null");
            return (Criteria) this;
        }

        public Criteria andClassStatusEqualTo(String value) {
            addCriterion("class_status =", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotEqualTo(String value) {
            addCriterion("class_status <>", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusGreaterThan(String value) {
            addCriterion("class_status >", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusGreaterThanOrEqualTo(String value) {
            addCriterion("class_status >=", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusLessThan(String value) {
            addCriterion("class_status <", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusLessThanOrEqualTo(String value) {
            addCriterion("class_status <=", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusLike(String value) {
            addCriterion("class_status like", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotLike(String value) {
            addCriterion("class_status not like", value, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusIn(List<String> values) {
            addCriterion("class_status in", values, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotIn(List<String> values) {
            addCriterion("class_status not in", values, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusBetween(String value1, String value2) {
            addCriterion("class_status between", value1, value2, "classStatus");
            return (Criteria) this;
        }

        public Criteria andClassStatusNotBetween(String value1, String value2) {
            addCriterion("class_status not between", value1, value2, "classStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIsMondayIsNull() {
            addCriterion("is_monday is null");
            return (Criteria) this;
        }

        public Criteria andIsMondayIsNotNull() {
            addCriterion("is_monday is not null");
            return (Criteria) this;
        }

        public Criteria andIsMondayEqualTo(Integer value) {
            addCriterion("is_monday =", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotEqualTo(Integer value) {
            addCriterion("is_monday <>", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayGreaterThan(Integer value) {
            addCriterion("is_monday >", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_monday >=", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayLessThan(Integer value) {
            addCriterion("is_monday <", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayLessThanOrEqualTo(Integer value) {
            addCriterion("is_monday <=", value, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayIn(List<Integer> values) {
            addCriterion("is_monday in", values, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotIn(List<Integer> values) {
            addCriterion("is_monday not in", values, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayBetween(Integer value1, Integer value2) {
            addCriterion("is_monday between", value1, value2, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsMondayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_monday not between", value1, value2, "isMonday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIsNull() {
            addCriterion("is_tuesday is null");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIsNotNull() {
            addCriterion("is_tuesday is not null");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayEqualTo(Integer value) {
            addCriterion("is_tuesday =", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotEqualTo(Integer value) {
            addCriterion("is_tuesday <>", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayGreaterThan(Integer value) {
            addCriterion("is_tuesday >", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_tuesday >=", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayLessThan(Integer value) {
            addCriterion("is_tuesday <", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayLessThanOrEqualTo(Integer value) {
            addCriterion("is_tuesday <=", value, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayIn(List<Integer> values) {
            addCriterion("is_tuesday in", values, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotIn(List<Integer> values) {
            addCriterion("is_tuesday not in", values, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayBetween(Integer value1, Integer value2) {
            addCriterion("is_tuesday between", value1, value2, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsTuesdayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_tuesday not between", value1, value2, "isTuesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIsNull() {
            addCriterion("is_wednesday is null");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIsNotNull() {
            addCriterion("is_wednesday is not null");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayEqualTo(Integer value) {
            addCriterion("is_wednesday =", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotEqualTo(Integer value) {
            addCriterion("is_wednesday <>", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayGreaterThan(Integer value) {
            addCriterion("is_wednesday >", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_wednesday >=", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayLessThan(Integer value) {
            addCriterion("is_wednesday <", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayLessThanOrEqualTo(Integer value) {
            addCriterion("is_wednesday <=", value, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayIn(List<Integer> values) {
            addCriterion("is_wednesday in", values, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotIn(List<Integer> values) {
            addCriterion("is_wednesday not in", values, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayBetween(Integer value1, Integer value2) {
            addCriterion("is_wednesday between", value1, value2, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsWednesdayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_wednesday not between", value1, value2, "isWednesday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIsNull() {
            addCriterion("is_thursday is null");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIsNotNull() {
            addCriterion("is_thursday is not null");
            return (Criteria) this;
        }

        public Criteria andIsThursdayEqualTo(Integer value) {
            addCriterion("is_thursday =", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotEqualTo(Integer value) {
            addCriterion("is_thursday <>", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayGreaterThan(Integer value) {
            addCriterion("is_thursday >", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_thursday >=", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayLessThan(Integer value) {
            addCriterion("is_thursday <", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayLessThanOrEqualTo(Integer value) {
            addCriterion("is_thursday <=", value, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayIn(List<Integer> values) {
            addCriterion("is_thursday in", values, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotIn(List<Integer> values) {
            addCriterion("is_thursday not in", values, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayBetween(Integer value1, Integer value2) {
            addCriterion("is_thursday between", value1, value2, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsThursdayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_thursday not between", value1, value2, "isThursday");
            return (Criteria) this;
        }

        public Criteria andIsFridayIsNull() {
            addCriterion("is_friday is null");
            return (Criteria) this;
        }

        public Criteria andIsFridayIsNotNull() {
            addCriterion("is_friday is not null");
            return (Criteria) this;
        }

        public Criteria andIsFridayEqualTo(Integer value) {
            addCriterion("is_friday =", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotEqualTo(Integer value) {
            addCriterion("is_friday <>", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayGreaterThan(Integer value) {
            addCriterion("is_friday >", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_friday >=", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayLessThan(Integer value) {
            addCriterion("is_friday <", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayLessThanOrEqualTo(Integer value) {
            addCriterion("is_friday <=", value, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayIn(List<Integer> values) {
            addCriterion("is_friday in", values, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotIn(List<Integer> values) {
            addCriterion("is_friday not in", values, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayBetween(Integer value1, Integer value2) {
            addCriterion("is_friday between", value1, value2, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsFridayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_friday not between", value1, value2, "isFriday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIsNull() {
            addCriterion("is_saturday is null");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIsNotNull() {
            addCriterion("is_saturday is not null");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayEqualTo(Integer value) {
            addCriterion("is_saturday =", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotEqualTo(Integer value) {
            addCriterion("is_saturday <>", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayGreaterThan(Integer value) {
            addCriterion("is_saturday >", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_saturday >=", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayLessThan(Integer value) {
            addCriterion("is_saturday <", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayLessThanOrEqualTo(Integer value) {
            addCriterion("is_saturday <=", value, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayIn(List<Integer> values) {
            addCriterion("is_saturday in", values, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotIn(List<Integer> values) {
            addCriterion("is_saturday not in", values, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayBetween(Integer value1, Integer value2) {
            addCriterion("is_saturday between", value1, value2, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSaturdayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_saturday not between", value1, value2, "isSaturday");
            return (Criteria) this;
        }

        public Criteria andIsSundayIsNull() {
            addCriterion("is_sunday is null");
            return (Criteria) this;
        }

        public Criteria andIsSundayIsNotNull() {
            addCriterion("is_sunday is not null");
            return (Criteria) this;
        }

        public Criteria andIsSundayEqualTo(Integer value) {
            addCriterion("is_sunday =", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotEqualTo(Integer value) {
            addCriterion("is_sunday <>", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayGreaterThan(Integer value) {
            addCriterion("is_sunday >", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_sunday >=", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayLessThan(Integer value) {
            addCriterion("is_sunday <", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayLessThanOrEqualTo(Integer value) {
            addCriterion("is_sunday <=", value, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayIn(List<Integer> values) {
            addCriterion("is_sunday in", values, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotIn(List<Integer> values) {
            addCriterion("is_sunday not in", values, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayBetween(Integer value1, Integer value2) {
            addCriterion("is_sunday between", value1, value2, "isSunday");
            return (Criteria) this;
        }

        public Criteria andIsSundayNotBetween(Integer value1, Integer value2) {
            addCriterion("is_sunday not between", value1, value2, "isSunday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_class
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_class
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}