package com.slianOAsys.model;

import java.util.ArrayList;
import java.util.List;

public class SlianoaAttendanceRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public SlianoaAttendanceRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(Integer value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(Integer value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(Integer value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(Integer value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<Integer> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<Integer> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeIsNull() {
            addCriterion("record_signtime is null");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeIsNotNull() {
            addCriterion("record_signtime is not null");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeEqualTo(String value) {
            addCriterion("record_signtime =", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeNotEqualTo(String value) {
            addCriterion("record_signtime <>", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeGreaterThan(String value) {
            addCriterion("record_signtime >", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeGreaterThanOrEqualTo(String value) {
            addCriterion("record_signtime >=", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeLessThan(String value) {
            addCriterion("record_signtime <", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeLessThanOrEqualTo(String value) {
            addCriterion("record_signtime <=", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeLike(String value) {
            addCriterion("record_signtime like", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeNotLike(String value) {
            addCriterion("record_signtime not like", value, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeIn(List<String> values) {
            addCriterion("record_signtime in", values, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeNotIn(List<String> values) {
            addCriterion("record_signtime not in", values, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeBetween(String value1, String value2) {
            addCriterion("record_signtime between", value1, value2, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSigntimeNotBetween(String value1, String value2) {
            addCriterion("record_signtime not between", value1, value2, "recordSigntime");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressIsNull() {
            addCriterion("record_signaddress is null");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressIsNotNull() {
            addCriterion("record_signaddress is not null");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressEqualTo(String value) {
            addCriterion("record_signaddress =", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressNotEqualTo(String value) {
            addCriterion("record_signaddress <>", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressGreaterThan(String value) {
            addCriterion("record_signaddress >", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressGreaterThanOrEqualTo(String value) {
            addCriterion("record_signaddress >=", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressLessThan(String value) {
            addCriterion("record_signaddress <", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressLessThanOrEqualTo(String value) {
            addCriterion("record_signaddress <=", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressLike(String value) {
            addCriterion("record_signaddress like", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressNotLike(String value) {
            addCriterion("record_signaddress not like", value, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressIn(List<String> values) {
            addCriterion("record_signaddress in", values, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressNotIn(List<String> values) {
            addCriterion("record_signaddress not in", values, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressBetween(String value1, String value2) {
            addCriterion("record_signaddress between", value1, value2, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignaddressNotBetween(String value1, String value2) {
            addCriterion("record_signaddress not between", value1, value2, "recordSignaddress");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusIsNull() {
            addCriterion("record_signstatus is null");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusIsNotNull() {
            addCriterion("record_signstatus is not null");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusEqualTo(String value) {
            addCriterion("record_signstatus =", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusNotEqualTo(String value) {
            addCriterion("record_signstatus <>", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusGreaterThan(String value) {
            addCriterion("record_signstatus >", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusGreaterThanOrEqualTo(String value) {
            addCriterion("record_signstatus >=", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusLessThan(String value) {
            addCriterion("record_signstatus <", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusLessThanOrEqualTo(String value) {
            addCriterion("record_signstatus <=", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusLike(String value) {
            addCriterion("record_signstatus like", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusNotLike(String value) {
            addCriterion("record_signstatus not like", value, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusIn(List<String> values) {
            addCriterion("record_signstatus in", values, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusNotIn(List<String> values) {
            addCriterion("record_signstatus not in", values, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusBetween(String value1, String value2) {
            addCriterion("record_signstatus between", value1, value2, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordSignstatusNotBetween(String value1, String value2) {
            addCriterion("record_signstatus not between", value1, value2, "recordSignstatus");
            return (Criteria) this;
        }

        public Criteria andRecordWechatIsNull() {
            addCriterion("record_wechat is null");
            return (Criteria) this;
        }

        public Criteria andRecordWechatIsNotNull() {
            addCriterion("record_wechat is not null");
            return (Criteria) this;
        }

        public Criteria andRecordWechatEqualTo(String value) {
            addCriterion("record_wechat =", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatNotEqualTo(String value) {
            addCriterion("record_wechat <>", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatGreaterThan(String value) {
            addCriterion("record_wechat >", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatGreaterThanOrEqualTo(String value) {
            addCriterion("record_wechat >=", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatLessThan(String value) {
            addCriterion("record_wechat <", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatLessThanOrEqualTo(String value) {
            addCriterion("record_wechat <=", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatLike(String value) {
            addCriterion("record_wechat like", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatNotLike(String value) {
            addCriterion("record_wechat not like", value, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatIn(List<String> values) {
            addCriterion("record_wechat in", values, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatNotIn(List<String> values) {
            addCriterion("record_wechat not in", values, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatBetween(String value1, String value2) {
            addCriterion("record_wechat between", value1, value2, "recordWechat");
            return (Criteria) this;
        }

        public Criteria andRecordWechatNotBetween(String value1, String value2) {
            addCriterion("record_wechat not between", value1, value2, "recordWechat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table slianoa_attendance_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}