package com.slianOAsys.model;

public class SysRolesResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_resources.rr_id
     *
     * @mbggenerated
     */
    private Integer rrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_resources.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_resources.resources_id
     *
     * @mbggenerated
     */
    private Integer resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_resources.organization_id
     *
     * @mbggenerated
     */
    private Integer organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles_resources.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_resources.rr_id
     *
     * @return the value of sys_roles_resources.rr_id
     *
     * @mbggenerated
     */
    public Integer getRrId() {
        return rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_resources.rr_id
     *
     * @param rrId the value for sys_roles_resources.rr_id
     *
     * @mbggenerated
     */
    public void setRrId(Integer rrId) {
        this.rrId = rrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_resources.role_id
     *
     * @return the value of sys_roles_resources.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_resources.role_id
     *
     * @param roleId the value for sys_roles_resources.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_resources.resources_id
     *
     * @return the value of sys_roles_resources.resources_id
     *
     * @mbggenerated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_resources.resources_id
     *
     * @param resourcesId the value for sys_roles_resources.resources_id
     *
     * @mbggenerated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_resources.organization_id
     *
     * @return the value of sys_roles_resources.organization_id
     *
     * @mbggenerated
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_resources.organization_id
     *
     * @param organizationId the value for sys_roles_resources.organization_id
     *
     * @mbggenerated
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles_resources.status
     *
     * @return the value of sys_roles_resources.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles_resources.status
     *
     * @param status the value for sys_roles_resources.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}