package com.slianOAsys.model;

import java.util.ArrayList;

import java.util.List;

import com.slianOAsys.page.Page;

public class SysSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
protected Page page;
    
    public void setPage(Page page) {
        this.page=page;
    }

    public Page getPage() {
        return page;
    }
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public SysSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStKeyIsNull() {
            addCriterion("st_key is null");
            return (Criteria) this;
        }

        public Criteria andStKeyIsNotNull() {
            addCriterion("st_key is not null");
            return (Criteria) this;
        }

        public Criteria andStKeyEqualTo(String value) {
            addCriterion("st_key =", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyNotEqualTo(String value) {
            addCriterion("st_key <>", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyGreaterThan(String value) {
            addCriterion("st_key >", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyGreaterThanOrEqualTo(String value) {
            addCriterion("st_key >=", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyLessThan(String value) {
            addCriterion("st_key <", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyLessThanOrEqualTo(String value) {
            addCriterion("st_key <=", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyLike(String value) {
            addCriterion("st_key like", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyNotLike(String value) {
            addCriterion("st_key not like", value, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyIn(List<String> values) {
            addCriterion("st_key in", values, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyNotIn(List<String> values) {
            addCriterion("st_key not in", values, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyBetween(String value1, String value2) {
            addCriterion("st_key between", value1, value2, "stKey");
            return (Criteria) this;
        }

        public Criteria andStKeyNotBetween(String value1, String value2) {
            addCriterion("st_key not between", value1, value2, "stKey");
            return (Criteria) this;
        }

        public Criteria andStValueIsNull() {
            addCriterion("st_value is null");
            return (Criteria) this;
        }

        public Criteria andStValueIsNotNull() {
            addCriterion("st_value is not null");
            return (Criteria) this;
        }

        public Criteria andStValueEqualTo(String value) {
            addCriterion("st_value =", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueNotEqualTo(String value) {
            addCriterion("st_value <>", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueGreaterThan(String value) {
            addCriterion("st_value >", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueGreaterThanOrEqualTo(String value) {
            addCriterion("st_value >=", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueLessThan(String value) {
            addCriterion("st_value <", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueLessThanOrEqualTo(String value) {
            addCriterion("st_value <=", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueLike(String value) {
            addCriterion("st_value like", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueNotLike(String value) {
            addCriterion("st_value not like", value, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueIn(List<String> values) {
            addCriterion("st_value in", values, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueNotIn(List<String> values) {
            addCriterion("st_value not in", values, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueBetween(String value1, String value2) {
            addCriterion("st_value between", value1, value2, "stValue");
            return (Criteria) this;
        }

        public Criteria andStValueNotBetween(String value1, String value2) {
            addCriterion("st_value not between", value1, value2, "stValue");
            return (Criteria) this;
        }

        public Criteria andDecriptionIsNull() {
            addCriterion("decription is null");
            return (Criteria) this;
        }

        public Criteria andDecriptionIsNotNull() {
            addCriterion("decription is not null");
            return (Criteria) this;
        }

        public Criteria andDecriptionEqualTo(String value) {
            addCriterion("decription =", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotEqualTo(String value) {
            addCriterion("decription <>", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionGreaterThan(String value) {
            addCriterion("decription >", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionGreaterThanOrEqualTo(String value) {
            addCriterion("decription >=", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLessThan(String value) {
            addCriterion("decription <", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLessThanOrEqualTo(String value) {
            addCriterion("decription <=", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionLike(String value) {
            addCriterion("decription like", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotLike(String value) {
            addCriterion("decription not like", value, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionIn(List<String> values) {
            addCriterion("decription in", values, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotIn(List<String> values) {
            addCriterion("decription not in", values, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionBetween(String value1, String value2) {
            addCriterion("decription between", value1, value2, "decription");
            return (Criteria) this;
        }

        public Criteria andDecriptionNotBetween(String value1, String value2) {
            addCriterion("decription not between", value1, value2, "decription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_setting
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_setting
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}