package com.slianOAsys.model;

public class SysUsersRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.ur_id
     *
     * @mbggenerated
     */
    private Integer urId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_users_roles.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.ur_id
     *
     * @return the value of sys_users_roles.ur_id
     *
     * @mbggenerated
     */
    public Integer getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.ur_id
     *
     * @param urId the value for sys_users_roles.ur_id
     *
     * @mbggenerated
     */
    public void setUrId(Integer urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.user_id
     *
     * @return the value of sys_users_roles.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.user_id
     *
     * @param userId the value for sys_users_roles.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.role_id
     *
     * @return the value of sys_users_roles.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.role_id
     *
     * @param roleId the value for sys_users_roles.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_users_roles.status
     *
     * @return the value of sys_users_roles.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_users_roles.status
     *
     * @param status the value for sys_users_roles.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}